-- CREATE DATABASE`BLOG ipb-22`;
/*
CREATE TABLE posts (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(255) NOT NULL
);
*/

INSERT INTO posts
(TITLE)
VALUE
("My First Blog Post"),
("My Second Blog Post");